import type { Metadata } from "next";
import Navbar from "@/app/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full flex flex-col bg-zinc-950 text-zinc-100">
        <Navbar></Navbar>
        {children}
    </div>
  );
}
