import { Metadata } from "next";
import Link from "next/link";
import PricingCard from "../components/pricing-card";
import { 
  Folder, 
  FileText, 
  Share2, 
  LayoutDashboard, 
  Terminal, 
  ShieldCheck, 
  Check 
} from "lucide-react"
import FeatureCard from "../components/feature-card";


export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-zinc-950 text-zinc-100">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[600px] bg-emerald-500/10 blur-[140px] rounded-full pointer-events-none" />
      {/* HERO */}
      <section className="mx-auto max-w-6xl px-6 py-24 text-center">
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight">
          Organize Your Files
          <span className="text-emerald-500"> Smarter</span>
        </h1>

        <p className="mt-6 text-zinc-400 max-w-2xl mx-auto">
          AssetHub is a modern platform for managing files, folders and shared
          assets. Organize everything in one secure dashboard and collaborate
          with your team effortlessly.
        </p>

        <div className="mt-10 flex justify-center gap-4">
          <Link
            href="/register"
            className="rounded-lg bg-emerald-500 px-6 py-3 text-sm font-medium text-white hover:bg-emerald-600 transition"
          >
            Get Started
          </Link>

          <Link
            href="#features"
            className="rounded-lg border border-zinc-800 px-6 py-3 text-sm text-zinc-300 hover:bg-zinc-900 transition"
          >
            Explore Features
          </Link>
        </div>
      </section>

      {/* FEATURES */}
      <section
        id="features"
        className="mx-auto max-w-6xl px-6 py-24 border-t border-zinc-900"
      >
        <div className="text-center mb-16">
          <h2 className="text-3xl font-semibold">
            Powerful Features
          </h2>
          <p className="text-zinc-400 mt-4">
            Everything you need to manage and share digital assets.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">

          {/* Feature 1 */}

          <FeatureCard icon={<Folder size={36} />} title="Folder Management"
           description="Create and organize folders easily to structure all your digital
              assets in a clean and scalable way."/>


          {/* Feature 2 */}

          <FeatureCard icon={<FileText size={36} />} title="File Management"
           description="Upload, store and manage files securely inside your personal
              dashboard with full control."/>


          {/* Feature 3 */}

          <FeatureCard icon={<Share2 size={36} />} title="Share With Users"
           description="Share folders and files with other users securely and collaborate
              across teams."/>


          {/* Feature 4 */}

          <FeatureCard icon={<LayoutDashboard size={36} />} title="Powerful Dashboard"
           description="Manage everything from a clean and modern dashboard designed for
              productivity and speed."/>

          {/* Feature 5 */}

          <FeatureCard icon={<Terminal size={36} />} title="Developer API (Soon)"
           description="Access the full power of AssetHub through our API and integrate
              file management directly into your applications."/>

          {/* Feature 6 */}

          <FeatureCard icon={<ShieldCheck size={36} />} title="Secure Storage"
           description="Your files are stored securely with modern security practices and
              access control."/>

        </div>
      </section>

      {/* PRICING */}
      <section
        id="pricing"
        className="mx-auto max-w-6xl px-6 py-24 border-t border-zinc-900"
      >
        <div className="text-center mb-16">
          <h2 className="text-3xl font-semibold">Pricing</h2>
          <p className="text-zinc-400 mt-4">
            Start for free. More plans will be available soon.
          </p>
        </div>

        <PricingCard title="Free" price={0} description="Free while we are in early stage"
        features={[
          "File & Folder Management","Share With Users",
          "Dashboard Access","Developer API Access"
        ]}/>

        
      </section>

      {/* CTA */}
      <section className="border-t border-zinc-900">
        <div className="mx-auto max-w-6xl px-6 py-20 text-center">
          <h2 className="text-3xl font-semibold">
            Start Managing Your Assets Today
          </h2>

          <p className="text-zinc-400 mt-4">
            Create your account and organize files, folders and shared assets
            in one powerful platform.
          </p>

          <Link
            href="/register"
            className="mt-8 inline-block rounded-lg bg-emerald-500 px-6 py-3 text-sm font-medium text-white hover:bg-emerald-600 transition"
          >
            Create Free Account
          </Link>
        </div>
      </section>

    </main>
  );
}
