import type { Metadata } from "next";
import Sidebar from "@/app/components/sidebar"
import MobileSidebar from "../components/mobile-sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex overflow-hidden">
      
      <Sidebar />
      <MobileSidebar />

      <main className="flex-1 overflow-y-auto no-scrollbar">
        {children}
      </main>

    </div>
  );
}
